name: Build and Test Tartan Smart Home System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Java 
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Build Gradle
      run: |
        cd smart-home/Platform
        ./gradlew build

    - name: Run All Tests with Gradle
      run: |
        cd smart-home/Platform
        ./gradlew test 
    - name: Run Test Coverage
      run: |
        cd smart-home/Platform
        ./gradlew jacocoTestReport

    - name: Run PITest Mutation Testing
      run: |
        cd smart-home/Platform
        ./gradlew pitest

    - name: Upload PITest Reports
      uses: actions/upload-artifact@v2
      with:
          name: pitest-report
          path: smart-home/Platform/build/reports/pitest
          
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
          generate-branches-badge: true
          jacoco-csv-file: smart-home/Platform/build/reports/jacoco/test/jacocoTestReport.csv

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
          default_author: github_actions
          message: 'Commit Coverage Badge'
          add: '*.svg'

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
          name: jacoco-report
          path: build/reports/jacoco

    - name: Docker Build and Compose Up
      run: |
        cd smart-home
        docker-compose up --build -d
        sleep 30

    - name: Docker Compose Down
      run: |
        cd smart-home
        docker-compose down

  deploy:
     needs: build-and-test
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v1
       - name: Copy repo to cloud
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           port: ${{ secrets.PORT }}
           key: ${{ secrets.KEY }}
           source: "./"
           target: "~/prod"
       - name: Restart all instances on cloud
         uses: appleboy/ssh-action@master
         with: 
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           port: ${{ secrets.PORT }}
           key: ${{ secrets.KEY }}
           script: |
             cd ~/prod/smart-home
             git checkout origin/main
             docker-compose down && docker-compose up --build -d
